# Generated by Django 3.0 on 2019-12-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDNumber', models.CharField(max_length=11)),
                ('photo1', models.IntegerField(default=0)),
                ('photo2', models.IntegerField(default=0)),
                ('photo3', models.IntegerField(default=0)),
                ('sketch1', models.IntegerField(default=0)),
                ('sketch2', models.IntegerField(default=0)),
                ('sketch3', models.IntegerField(default=0)),
            ],
        ),
    ]
