# Generated by Django 3.0 on 2019-12-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='photo1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='photo2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='photo3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='sketch1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='sketch2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='sketch3',
            field=models.CharField(max_length=10),
        ),
    ]
