# Generated by Django 3.0 on 2019-12-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20191222_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='sketch1',
            new_name='drawing1',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='sketch2',
            new_name='drawing2',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='sketch3',
            new_name='drawing3',
        ),
    ]
