# Generated by Django 3.0 on 2019-12-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20191222_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='drawing1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='drawing2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='drawing3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='photo1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='photo2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='photo3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
